# Generated by Django 4.2.3 on 2023-07-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('join_date', models.DateField(auto_now_add=True, null=True)),
                ('subscription_ends', models.DateField(blank=True, null=True)),
                ('social_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
